# NumPy Random Module

The `numpy.random` module provides functions for generating random numbers for various distributions. This is extremely useful in a variety of circumstances, from simulating real-world data for testing, to initializing parameters in certain machine learning algorithms.

In [1]:
import numpy as np



## np.random.rand()

`np.random.rand()` generates uniformly distributed random numbers between 0 and 1. If no arguments are provided, a single float is returned. You can also specify the shape of the returned array by passing dimensions as arguments.



In [2]:
# Single random number
print(np.random.rand())

# 1D array of random numbers
print(np.random.rand(5))

# 2D array of random numbers
print(np.random.rand(3, 3))

0.9750033756169868
[0.16555704 0.22421255 0.62336029 0.43465871 0.0367092 ]
[[0.68928648 0.05228279 0.62073997]
 [0.21256411 0.47748713 0.72582256]
 [0.16786841 0.9184573  0.22806281]]



## np.random.randn()

`np.random.randn()` generates random numbers from the standard normal distribution. Usage is similar to `np.random.rand()`.


In [3]:
# Single random number
print(np.random.randn())

# 1D array of random numbers
print(np.random.randn(5))

# 2D array of random numbers
print(np.random.randn(3, 3))

-1.8001391163131617
[-0.81040709 -0.76633356 -0.35134693  0.36647296  0.28378928]
[[ 1.42069643  0.11279342 -0.88093649]
 [-0.12887352 -0.02079483 -0.1158043 ]
 [ 0.22221944  0.89420323 -0.60024783]]


## np.random.randint()

`np.random.randint()` generates random integers within a specified range.


In [ ]:
[low, high)

In [112]:
fruits = ['apple', 'banana', 'watermelon', 'cantaloupe' ]
rand_int = np.random.randint(len(fruits))

print(fruits[rand_int])

watermelon


In [4]:
# Single random integer between 0 and 10
print(np.random.randint(10))

# Single random integer between 5 and 10
print(np.random.randint(5, 10))

# 1D array of random integers between 0 and 10
print(np.random.randint(10, size=5))

2
6
[0 9 6 3 3]



## np.random.choice()

`np.random.choice()` generates a random sample from a given 1-D array.



In [146]:
# Randomly select from a list of numbers
print(np.random.choice([1, 2, 3, 4, 5]))

# Randomly select multiple elements
print(np.random.choice([1, 2, 3, 4, 5], size=3))


2
[2 2 5]


In [212]:
np.random.choice(fruits, size=3)

array(['banana', 'cantaloupe', 'watermelon'], dtype='<U10')


## np.random.seed()

`np.random.seed()` sets the random seed, allowing random processes to be reproduced.



In [ ]:
np.random.seed(0)

print(np.random.rand(5))


## np.random.shuffle()

`np.random.shuffle()` randomly rearranges elements in a 1-D array.



In [213]:
arr = np.array([1, 2, 3, 4, 5])
np.random.shuffle(arr)
print(arr)

[3 4 5 1 2]


In [250]:
np.random.shuffle(arr)
print(arr)

[5 3 2 4 1]


In [252]:
arr2d = np.random.rand(3, 3)
print(arr2d)

[[0.35780051 0.4405747  0.44389253]
 [0.3024095  0.55432373 0.10271281]
 [0.43921671 0.60963618 0.07121813]]


In [302]:
np.random.shuffle(arr2d)
print(arr2d)

[[0.43921671 0.60963618 0.07121813]
 [0.3024095  0.55432373 0.10271281]
 [0.35780051 0.4405747  0.44389253]]



These are just a few of the functions offered by the `numpy.random` module. It offers a robust and flexible way to generate random numbers from various distributions.

# Numpy Files

In [306]:
# np.save() and np.load()

# save array
np.save('my_arrya.npy', arr2d)

# load array
np.load('my_arrya.npy')

array([[0.43921671, 0.60963618, 0.07121813],
       [0.3024095 , 0.55432373, 0.10271281],
       [0.35780051, 0.4405747 , 0.44389253]])

In [313]:
np.savetxt('my_array.txt', arr2d)

np.loadtxt('my_array.txt')

array([[0.43921671, 0.60963618, 0.07121813],
       [0.3024095 , 0.55432373, 0.10271281],
       [0.35780051, 0.4405747 , 0.44389253]])

In [314]:
# np.savetxt() and np.loadtxt()

np.savetxt('my_array.csv', arr2d, delimiter=',')

np.loadtxt('my_array.csv', delimiter=',')

array([[0.43921671, 0.60963618, 0.07121813],
       [0.3024095 , 0.55432373, 0.10271281],
       [0.35780051, 0.4405747 , 0.44389253]])

In [321]:
# np.savez() and np.load()

np.savez('my_multiple_arrays.npz', arr1=arr, arr2=arr2d)

np.savez_compressed('my_multiple_arrays_compressed.npz', arr1=arr, arr2=arr2d)


loaded_arrays = np.load('my_multiple_arrays.npz')

In [318]:
loaded_arrays.files

['arr1', 'arr2']

In [320]:
loaded_arrays['arr2']

array([[0.43921671, 0.60963618, 0.07121813],
       [0.3024095 , 0.55432373, 0.10271281],
       [0.35780051, 0.4405747 , 0.44389253]])

> Content created by [**Carlos Cruz-Maldonado**](https://www.linkedin.com/in/carloscruzmaldonado/).  
> I am available to answer any questions or provide further assistance.   
> Feel free to reach out to me at any time.  